apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xp.fullname" . }}
  labels:
    {{- include "xp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.xpTreatment.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "xp.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ template "xp.name" . }}
        release: {{ .Release.Name }}
        {{- include "xp.labels" . | nindent 8 }}
      {{- with .Values.xpTreatment.annotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.xpTreatment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: xp-treatment
        image: "{{ .Values.xpTreatment.image.registry }}{{ .Values.xpTreatment.image.repository }}:{{ .Values.xpTreatment.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.xpTreatment.image.pullPolicy }}
        env:
          {{- with .Values.xpTreatment.extraEnvs }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.xpTreatment.livenessProbe.path }}
            port: {{ .Values.xpTreatment.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.xpTreatment.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.xpTreatment.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.xpTreatment.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.xpTreatment.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.xpTreatment.readinessProbe.path }}
            port: {{ .Values.xpTreatment.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.xpTreatment.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.xpTreatment.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.xpTreatment.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.xpTreatment.readinessProbe.timeoutSeconds }}
        resources:
          {{- toYaml .Values.xpTreatment.resources | nindent 12 }}
        # Give time for running pods to terminate existing connection before letting
        # Kubernetes terminate the pods.
        # https://blog.sebastian-daschner.com/entries/zero-downtime-updates-kubernetes
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "sleep 15"]
        args:
        - serve
        - --config=/etc/xp/config.yaml
        {{- with .Values.xpTreatment.extraArgs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/xp
        {{- with .Values.xpTreatment.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.swaggerUi.enabled }}
      - name: swagger-ui
        image: "swaggerapi/swagger-ui:{{ .Values.swaggerUi.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.swaggerUi.service.internalPort }}
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        env:
        - name: LAYOUT
          value: "BaseLayout"
        - name: SWAGGER_JSON
          value: "/app/treatment.yaml"
        - name: PORT
          value: "{{ .Values.swaggerUi.service.internalPort }}"
        - name: API_SERVER
          value: "{{ .Values.swaggerUi.apiServer }}"
        command: ["sh", "-c"]
        args:
        - |
          mkdir /app
          export LOCAL_API_SERVER="http://127.0.0.1:{{ .Values.xpTreatment.service.internalPort }}"
          echo "Fetching swagger configuration from ${LOCAL_API_SERVER}/treatment.yaml..."
          until $$(wget -O $${SWAGGER_JSON} --tries 1 --timeout 1 ${LOCAL_API_SERVER}/treatment.yaml); do
            printf '.'
            sleep 10
          done
          echo "Fetching swagger configuration from ${LOCAL_API_SERVER}/schema.yaml..."
          until $$(wget -O /app/schema.yaml --tries 1 --timeout 1 ${LOCAL_API_SERVER}/schema.yaml); do
            printf '.'
            sleep 10
          done
          echo "Update Swagger config..."
          sed -r -i 's%^((\s*)-(\s*)url\s*:).*$$%\1 "'$${API_SERVER}'"%' $${SWAGGER_JSON}
          echo "Running Swagger UI..."
          /usr/share/nginx/run.sh
      {{- end }}
      volumes:
      - name: config 
        secret:
          secretName: {{ template "xp.fullname" .}}-config
      {{- with .Values.xpTreatment.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}

{{- if .Values.xpTreatment.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.xpTreatment.nodeSelector | nindent 8 }}
{{ end -}}
