apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "xp.fullname" .}}-config
stringData:
  config.yaml: |
    {{- toYaml .Values.xpTreatment.config | nindent 4 -}}
