apiVersion: v1
kind: Service
metadata:
  name: {{ include "xp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "xp.fullname" .}}
    chart: {{ template "xp.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{ if .Values.xpTreatment.labels -}}
{{ toYaml .Values.xpTreatment.labels | indent 4 -}}
{{- end }}
spec:
  type: {{ .Values.xpTreatment.service.type }}
  ports:
    - name: http
      port: {{ .Values.xpTreatment.service.externalPort }}
      targetPort: {{ .Values.xpTreatment.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "xp.name" .}}
    release: {{ .Release.Name }}
