run:
  build-tags:
    - e2e
    - integration
  skip-files:
    - clients/management/managementclient.go
    - clients/treatment/treatmentclient.go

linters:
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - structcheck
    - unused
    - varcheck

linters-settings:
  lll:
    line-length: 150
