default_stages:
  - push
repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.0
    hooks:
      - id: helm-docs-built
        name: 'Helm Docs for XP Management Service Chart'
        files: '^infra/charts/management-service/'
        args:
          - --chart-search-root='infra/charts/management-service'
          - --template-files=./README.md.gotmpl
      - id: helm-docs-built
        name: 'Helm Docs for XP Treatment Service Chart'
        files: '^infra/charts/treatment-service/'
        args:
          - --chart-search-root='infra/charts/treatment-service'
          - --template-files=./README.md.gotmpl
  - repo: local
    hooks:
      - id: format
        name: Format
        stages: [ push ]
        language: system
        entry: make format
        pass_filenames: false
      - id: lint
        name: Lint
        stages: [ push ]
        language: system
        entry: make lint
        pass_filenames: false
  - repo: local
    hooks:
      - id: prettier
        name: 'Prettier for UI'
        files: '^ui/'
        types_or: [javascript, css]
        language: system
        entry: bash -c 'cd ui && yarn lint'
