repos:
  - repo: local
    hooks:
      - id: format
        name: Format
        stages: [ push ]
        language: system
        entry: make format
        pass_filenames: false
      - id: lint
        name: Lint
        stages: [ push ]
        language: system
        entry: make lint
        pass_filenames: false
  - repo: local
    hooks:
      - id: prettier
        name: 'Prettier for UI'
        files: '^ui/'
        types_or: [javascript, css]
        language: system
        entry: bash -c 'cd ui && yarn lint'
