version: '3'
services:
  postgres:
    image: postgres:13-alpine
    container_name: xp_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=xp
      - POSTGRES_PASSWORD=xp
      - POSTGRES_DB=xp

  pubsub:
    image: google/cloud-sdk:349.0.0
    container_name: xp_pubsub
    ports:
      - 8085:8085
    command:
      gcloud beta emulators pubsub start --host-port 0.0.0.0:8085 --project dev

  swagger-ui:
    image: swaggerapi/swagger-ui:v3.47.1
    container_name: xp_swagger-ui
    ports:
      - 8081:5555
    volumes:
      - ./api:/usr/share/nginx/html/docs
    environment:
      - PORT=5555
      - Layour=BaseLayout
      - "URLS=[{ name:'management-service',url:'./docs/experiments.yaml'}, {name:'treatment-service',url:'./docs/treatment.yaml' }]"

  postgres-auth:
    image: bitnami/postgresql:11.6.0-debian-9-r0
    container_name: xp_postgres-auth
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=oryketo
      - POSTGRESQL_PASSWORD=oryketo
      - POSTGRESQL_DATABASE=oryketo

  keto-server:
    image: oryd/keto:v0.4.3
    container_name: xp_keto-server
    ports:
      - 4466:4466
    environment:
      - DSN=postgres://oryketo:oryketo@postgres-auth:5432/oryketo?sslmode=disable
      - LOG_LEVEL=debug

  keto-server-bootstrap-policies:
    image: oryd/keto:v0.4.3
    volumes:
      - ./keto/policies:/policies
    environment:
      - LOG_LEVEL=debug
      - KETO_URL=http://xp_keto-server:4466
