version: '3'
services:
  postgres:
    image: postgres:13-alpine
    container_name: xp_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=xp
      - POSTGRES_PASSWORD=xp
      - POSTGRES_DB=xp

  pubsub:
    image: google/cloud-sdk:349.0.0
    container_name: xp_pubsub
    ports:
      - 8085:8085
    command:
      gcloud beta emulators pubsub start --host-port 0.0.0.0:8085 --project dev

  swagger-ui:
    image: swaggerapi/swagger-ui:v3.47.1
    container_name: xp_swagger-ui
    ports:
      - 8081:5555
    volumes:
      - ./api:/usr/share/nginx/html/docs
    environment:
      - PORT=5555
      - Layour=BaseLayout
      - "URLS=[{ name:'management-service',url:'./docs/experiments.yaml'}, {name:'treatment-service',url:'./docs/treatment.yaml' }]"
