{{- if .Values.xpApi.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "xp.fullname" .}}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.xpApi.ingress.class }}
    ingress.class: {{ . }}
    {{- end }}
  labels:
    app: {{ include "xp.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    helm.sh/chart: {{ include "xp.chart" . }}
    app.kubernetes.io/name: {{ include "xp.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.xpApi.labels }}
{{ toYaml .Values.xpApi.labels | indent 4 }}
{{- end }}
spec:
  rules:
  - {{- with .Values.xpApi.ingress.host }}
    host: {{ . }}
    {{- end }} 
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ template "xp.fullname" .}}
            servicePort: {{ .Values.xpApi.service.externalPort }}
{{- end }}
