apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "xp.fullname" .}}-api-config
stringData:
  config.yaml: |
    {{- toYaml .Values.xpApi.config | nindent 4 -}}
  {{- if .Values.xpApi.uiConfig }}
  ui.config.json: |
    {{- include "xp.ui.config" . | nindent 4 -}}
  {{- end }}
