{{- if .Values.xpManagement.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xp.serviceAccountName" . }}
  labels:
    {{- include "xp.labels" . | nindent 4 }}
  {{- with .Values.xpManagement.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
