apiVersion: v1
kind: Service
metadata:
  name: {{ template "xp.fullname" .}}-swagger
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "xp.fullname" .}}
    chart: {{ template "xp.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{ if .Values.xpApi.labels -}}
{{ toYaml .Values.xpApi.labels | indent 4 -}}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.swaggerUi.service.externalPort }}
      targetPort: {{ .Values.swaggerUi.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "xp.fullname" .}}
    release: {{ .Release.Name }}
