name: Test Dependencies
description: Configure necessary steps for running CI tests

inputs:
  go-version:
    required: true
    description: 'Go Version to use for test workflows'

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache-dependency-path: "**/go.sum"

    # Since Github actions' services don't expose command like how docker-compose does, we'll need to
    # start Google Pubsub Emulator separately since it requires running the command
    # Related schema: https://json.schemastore.org/github-workflow.json
    - name: Setup PubSub emulator
      shell: bash
      run: ./.github/emulator/start-emulator.sh pubsub
