openapi: 3.0.1
info:
  title: Experimentation Treatment API
  description: API for fetching the treatment
  version: v1
servers:
  - url: /v1
tags: []
paths:
  /projects/{project_id}/fetch-treatment:
    post:
      operationId: FetchTreatment
      tags:
        - fetch treatment
      summary: Fetch treatment for the given request parameters and project
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: pass-key
          in: header
          required: true
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/FetchTreatmentRequestBody'
      responses:
        200:
          $ref: '#/components/responses/FetchTreatmentSuccess'
        400:
          $ref: '#/components/responses/FetchTreatmentBadRequest'
        500:
          $ref: '#/components/responses/InternalServerError'
      x-codegen-request-body-name: FetchTreatmentRequestBody

components:
  requestBodies:
    FetchTreatmentRequestBody:
      content:
        application/json:
          schema:
            type: object
            additionalProperties:
              oneOf:
                - type: string
                - type: integer
                  format: int64
                - type: boolean
          examples:
            allSegmenters:
              description: |
                An example request body showing the input experiment variables, if all segmenters are used.
                In this example, the randomization key is the `order-id`. The other variables are converted to
                the respective segmenters configured in the project and match the corresponding experiment. 
              value:
                country_code: "SG"
                service_type: 66
                latitude: 1.3324
                longitude: 104.0391
                tz: "Asia/Singapore"
                priority_allocation: true
                order-id: "abc123"
      required: true

  responses:
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: 'schema.yaml#/components/schemas/Error'
    FetchTreatmentBadRequest:
      description: Bad request
      headers:
        XP-Request-ID:
          schema:
            type: string
          description: Autogenerated uuid for each Fetch Treatment request
      content:
        application/json:
          schema:
            $ref: 'schema.yaml#/components/schemas/Error'
    FetchTreatmentSuccess:
      description: Fetch treatment for a given project
      headers:
        XP-Request-ID:
          schema:
            type: string
          description: Autogenerated uuid for each Fetch Treatment request
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: 'schema.yaml#/components/schemas/SelectedTreatment'
          examples:
            treatmentAssigned:
              description: |
                An example response body for when an experiment could be matched for the given request,
                and a treatment is assigned.
              value:
                data:
                  experiment_id: 1234
                  experiment_name: "ID-experiment-weekday-1"
                  treatment:
                    name: treatment-A
                    configuration:
                      control: false
                      weight: 0.3
                    traffic: 20
            noExperimentMatched:
              description: |
                An example response body for when no active experiment could be matched for the given segmenters
                and thus, no treatment could be assigned.
              value: {} # Empty JSON
