name: linter

on: pull_request

jobs:
  lint-python:
    runs-on: ubuntu-latest
    env:
      PYTHON: 3.7
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: x64
      - name: Install dependencies
        run: make install-python-ci-dependencies
      - name: Lint python
        run: make lint-python

  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Lint Common module
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          working-directory: common
          skip-go-installation: true
          args: --timeout 3m --verbose
      - name: Lint Management Service module
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          working-directory: management-service
          skip-go-installation: true
          args: --timeout 3m --verbose
      - name: Lint Treatment Service module
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          working-directory: treatment-service
          skip-go-installation: true
          args: --timeout 3m --verbose
