name: Release Trigger

on:
  # Automatically run CI on Release and Pre-Release tags and main branch
  # (except changes to non-relevant paths)
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - main
    paths-ignore:
      - "plugins/**"
      - ".github/workflows/plugins.yml"
  
  # To make it possible to trigger release CI workflow for any arbitrary git ref
  workflow_dispatch:
  
jobs:
  release-rules:
    runs-on: ubuntu-latest
    outputs:
      release-type: ${{ steps.release-rules.outputs.release-type }}
    steps:
      - uses: actions/checkout@v3
      - id: release-rules
        uses: ./.github/actions/release-rules

  release:
   # Automatically publish release and pre-release artifacts.
   #
   # As for dev releases, make it possible to publish artifacts
   # manually by approving 'deployment' in the 'manual' environment.
   #
   # Dev build can be released either from the 'main' branch or
   # by running this workflow manually with `workflow_dispatch` event.
    if: >-
      contains('release,pre-release', needs.release-rules.outputs.release-type)
        || ( github.event_name != 'pull_request' )
        || ( github.event.pull_request.head.repo.full_name == github.repository )
    needs:
      - release-rules
    uses: ./.github/workflows/release.yml
    with:
      environment: ${{ needs.release-rules.outputs.release-type == 'dev' && 'manual' || '' }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
