name: XP Release CI

on:
  workflow_call:
    inputs:
      management_service_version:
        required: true
        type: string
        description: Semantic version of xp-management artifact to be published
      treatment_service_version:
        required: true
        type: string
        description: Semantic version of xp-treatment artifact to be published
      container_registry:
        type: string
        required: false
        default: ghcr.io
      environment:
        type: string
        required: false
    secrets:
      ghcr_token:
        required: true

jobs:
  publish-management-service:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.container_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.ghcr_token }}

      - name: Download Docker image tar
        uses: actions/download-artifact@v2
        with:
          name: xp-management.${{ inputs.management_service_version }}.tar

      - name: Publish Docker Image
        env:
          DOCKER_REPOSITORY: ${{ inputs.container_registry }}/${{ github.repository }}
        run: |
          docker image load --input xp-management.${{ inputs.management_service_version }}.tar
          docker tag \
            xp-management:${{ inputs.management_service_version }} \
            ${{ env.DOCKER_REPOSITORY }}/xp-management:${{ inputs.management_service_version }}
          docker push ${{ env.DOCKER_REPOSITORY }}/xp-management:${{ inputs.management_service_version }}
  
  publish-treatment-service:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.container_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.ghcr_token }}

      - name: Download Docker image tar
        uses: actions/download-artifact@v2
        with:
          name: xp-treatment.${{ inputs.treatment_service_version }}.tar

      - name: Publish Docker Image
        env:
          DOCKER_REPOSITORY: ${{ inputs.container_registry }}/${{ github.repository }}
        run: |
          docker image load --input xp-treatment.${{ inputs.treatment_service_version }}.tar
          docker tag \
            xp-treatment:${{ inputs.treatment_service_version }} \
            ${{ env.DOCKER_REPOSITORY }}/xp-treatment:${{ inputs.treatment_service_version }}
          docker push ${{ env.DOCKER_REPOSITORY }}/xp-treatment:${{ inputs.treatment_service_version }}
