name: CI

on:
  # Automatically run CI on Release and Pre-Release tags and main branch
  # (except changes to non-relevant paths)
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - main

  # Automatically run CI on branches, that have active PR opened
  pull_request:
    branches:
      - main

jobs:
  lint-python:
    runs-on: ubuntu-latest
    env:
      PYTHON: 3.7
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: x64
      - name: Install dependencies
        run: make install-python-ci-dependencies
      - name: Lint python
        run: make lint-python

  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Lint Common module
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          working-directory: common
          skip-go-installation: true
          args: --timeout 3m --verbose
      - name: Lint Management Service module
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          working-directory: management-service
          skip-go-installation: true
          args: --timeout 3m --verbose
      - name: Lint Treatment Service module
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          working-directory: treatment-service
          skip-go-installation: true
          args: --timeout 3m --verbose

  unit-tests-management:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/api/.go
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: xp
          POSTGRES_USER: xp
          POSTGRES_PASSWORD: xp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Test Dependencies
        uses: ./.github/actions/setup-tests
      
      - name: Run Management Service test
        env:
          DATABASE_HOST: localhost
          DATABASE_NAME: xp
          DATABASE_USER: xp
          DATABASE_PASSWORD: xp
        run: make test-management-service

  unit-tests-treatment:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/api/.go
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: xp
          POSTGRES_USER: xp
          POSTGRES_PASSWORD: xp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Test Dependencies
        uses: ./.github/actions/setup-tests
      
      - name: Run Treatment Service test
        env:
          DATABASE_HOST: localhost
          DATABASE_NAME: xp
          DATABASE_USER: xp
          DATABASE_PASSWORD: xp
        run: make test-treatment-service

  e2e-tests:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/api/.go
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: xp
          POSTGRES_USER: xp
          POSTGRES_PASSWORD: xp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Test Dependencies
        uses: ./.github/actions/setup-tests
      
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: x64

      - name: Install dependencies
        run: make install-python-ci-dependencies
      
      - name: Build binaries
        run: make build

      - name: Run E2E tests
        env:
          DATABASE_HOST: localhost
          DATABASE_NAME: xp
          DATABASE_USER: xp
          DATABASE_PASSWORD: xp
        run: make e2e-ci
